import React from "react";
import Footer from "../Footer/Footer";
import Head from "next/head";
import Script from "next/script";
import Navbar from "../Navbar/Navbar";
import styles from "../../styles/LayoutStyles/Layout.module.css";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Tokyo2021App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.children}>{children}</div>
      <Footer />
    </>
  );
};

export default Layout;
